<?php
/**
 * @file
 * datigov_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function datigov_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-81B1ToQ67qjBNcY0HHRVx53CSSQgXff0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '81B1ToQ67qjBNcY0HHRVx53CSSQgXff0',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-FP5UCgtOrJTbQod11rlllJxK9tEddDh5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'FP5UCgtOrJTbQod11rlllJxK9tEddDh5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-GfhmzHLhNmlUJp9LSFkVerPgTtj4QIRD'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'GfhmzHLhNmlUJp9LSFkVerPgTtj4QIRD',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-SRGU69EUQlPdT8GlLfTdqkAy00DmY2eo'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'SRGU69EUQlPdT8GlLfTdqkAy00DmY2eo',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-VBBDnNWYupC3PxCnXOq4e4ds4sAU4W7s'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'VBBDnNWYupC3PxCnXOq4e4ds4sAU4W7s',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-dqCRnp6cKP1cSzAsNB6zqFtY9AVEa0mp'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'dqCRnp6cKP1cSzAsNB6zqFtY9AVEa0mp',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-skesifO3aXpcndJY4lqBqXMuWuQF2Mr8'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'skesifO3aXpcndJY4lqBqXMuWuQF2Mr8',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-y0bmt1wN50B9oCuMeoazc1hpKiMkSQ2A'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'y0bmt1wN50B9oCuMeoazc1hpKiMkSQ2A',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-yW6mJ3GaJF0LypnLPa433Bf9GI8QdWd9'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'yW6mJ3GaJF0LypnLPa433Bf9GI8QdWd9',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'datigov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'datigov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
